from __future__ import annotations
import json
import math
import subprocess
from pathlib import Path


def probe_duration(path: Path) -> float:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "json", str(path)],
        check=True, capture_output=True, text=True,
    )
    return float(json.loads(out.stdout)["format"]["duration"])


def render(
    footage: list[Path],
    audio: Path,
    output: Path,
    resolution: str = "1280x720",
    music: Path | None = None,
    subtitles: Path | None = None,
    max_segment_seconds: float = 30.0,
) -> Path:
    """Spec item #9 video editing. Improvements over the original MVP:
    - uses ALL downloaded footage clips (looped/trimmed/cycled to span the
      narration at the requested cut rate), not just one segment per clip
    - optionally mixes a ducked background music bed under the narration
    - optionally burns in SRT captions generated by subtitles.py

    `max_segment_seconds` sets how often the footage cuts (what the user
    asked for): the number of segments is duration/max_segment_seconds
    rounded UP, so every segment is guaranteed <= max_segment_seconds --
    previously the cut rate was just duration/len(footage), so a 3-minute
    video with 5 downloaded clips cut only once every ~36 seconds
    regardless of format. If more segments are needed than there are
    distinct clips, clips are CYCLED (repeated) rather than limiting the
    edit to len(footage) segments; repeats start from a different point in
    the clip where possible so a repeated clip doesn't look like a frozen
    loop of the exact same frames.
    """
    output.parent.mkdir(parents=True, exist_ok=True)
    width, height = resolution.split("x", 1)
    duration = probe_duration(audio)
    clips = footage or []
    if not clips:
        raise RuntimeError("render() needs at least one footage clip.")
    num_segments = max(1, math.ceil(duration / max(1.0, max_segment_seconds)))
    segment = duration / num_segments  # guaranteed <= max_segment_seconds

    inputs: list[str] = []
    filter_parts: list[str] = []
    _clip_durations: dict[Path, float] = {}
    for i in range(num_segments):
        clip = clips[i % len(clips)]
        repeat_index = i // len(clips)
        start = 0.0
        if repeat_index > 0:
            # Best-effort start-point variation on repeat plays of the same
            # clip; falls back to 0.0 (a plain repeat) if the clip is
            # shorter than one segment or probing it fails for any reason
            # -- never worth failing the whole render over.
            try:
                full = _clip_durations.get(clip)
                if full is None:
                    full = _clip_durations[clip] = probe_duration(clip)
                if full > segment:
                    start = (repeat_index * segment) % max(1.0, full - segment)
            except Exception:
                start = 0.0
        seek_args = ["-ss", f"{start:.2f}"] if start else []
        inputs += ["-stream_loop", "-1", *seek_args, "-t", f"{segment:.2f}", "-i", str(clip)]
        # Crop-to-fill (scale up to cover the target frame, then crop the
        # excess) instead of pad-to-fit: B-roll is almost always horizontal
        # regardless of the target aspect ratio -- pad-to-fit used to leave
        # a vertical Short's footage pillarboxed with black bars on both
        # sides, which reads as unfinished/amateurish. Cropping the edges of
        # generic B-roll is the standard, safe tradeoff (nothing load-
        # bearing is usually framed at the very edge of stock footage).
        filter_parts.append(
            f"[{i}:v]scale={width}:{height}:force_original_aspect_ratio=increase,"
            f"crop={width}:{height},setsar=1,format=yuv420p[v{i}]"
        )
    concat_inputs = "".join(f"[v{i}]" for i in range(num_segments))
    filter_parts.append(f"{concat_inputs}concat=n={num_segments}:v=1:a=0[vcat]")
    video_label = "vcat"

    if subtitles and subtitles.exists():
        escaped = str(subtitles).replace("\\", "\\\\").replace(":", "\\:").replace("'", "\\'")
        filter_parts.append(f"[{video_label}]subtitles='{escaped}'[vsub]")
        video_label = "vsub"

    narration_idx = num_segments
    inputs += ["-i", str(audio)]
    has_music = bool(music and music.exists())
    if has_music:
        music_idx = narration_idx + 1
        inputs += ["-stream_loop", "-1", "-t", f"{duration:.2f}", "-i", str(music)]
        filter_parts.append(f"[{music_idx}:a]volume=0.12[music]")
        filter_parts.append(f"[{narration_idx}:a][music]amix=inputs=2:duration=first:dropout_transition=2[amixed]")
        audio_map = "[amixed]"
    else:
        audio_map = f"{narration_idx}:a"

    filter_complex = ";".join(filter_parts)
    cmd = [
        "ffmpeg", "-y", *inputs,
        "-filter_complex", filter_complex,
        "-map", f"[{video_label}]", "-map", audio_map,
        "-t", f"{duration:.2f}",
        "-c:v", "libx264", "-preset", "veryfast", "-c:a", "aac", "-movflags", "+faststart",
        str(output),
    ]
    subprocess.run(cmd, check=True)
    return output
